// Package codegen compiles a flow graph into a syslog-ng configuration.
package codegen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/syslog-yard/syslog-valve/internal/graph"
)

// Generate renders the full syslog-ng.conf for g. version is the
// "@version" directive value and should match the running syslog-ng
// (it tolerates older config versions with a warning, not the reverse).
func Generate(g *graph.Graph, version string) (string, error) {
	if err := g.Validate(); err != nil {
		return "", err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "@version: %s\n", version)
	b.WriteString("# Generated by syslog-valve — do not edit; change the graph instead.\n\n")
	b.WriteString("options {\n    keep-hostname(yes);\n    use-dns(no);\n    time-reopen(2);\n};\n")

	for _, n := range g.Nodes {
		switch n.Type {
		case graph.TypeSource:
			bind := n.Config.Bind
			if bind == "" {
				bind = "0.0.0.0"
			}
			fmt.Fprintf(&b, "\n# source %s\nsource s_%s {\n    network(ip(%q) transport(%q) port(%d));\n};\n",
				name(n), graph.Ident(n.ID), bind, n.Config.Transport, n.Config.Port)
		case graph.TypeForward:
			fmt.Fprintf(&b, "\n# forward %s\ndestination d_%s {\n    network(%q port(%d) transport(%q));\n};\n",
				name(n), graph.Ident(n.ID), n.Config.Host, n.Config.Port, n.Config.Transport)
		}
	}

	// One log path per wire keeps the mapping edge -> log {} trivial to
	// reason about and leaves room for per-path filters later.
	edges := append([]graph.Edge(nil), g.Edges...)
	sort.Slice(edges, func(i, j int) bool {
		if edges[i].From != edges[j].From {
			return edges[i].From < edges[j].From
		}
		return edges[i].To < edges[j].To
	})
	if len(edges) > 0 {
		b.WriteString("\n")
	}
	for _, e := range edges {
		fmt.Fprintf(&b, "log {\n    source(s_%s);\n    destination(d_%s);\n};\n",
			graph.Ident(e.From), graph.Ident(e.To))
	}
	return b.String(), nil
}

// Minimal returns a valid config with no flows, used before the first apply.
func Minimal(version string) string {
	return fmt.Sprintf("@version: %s\n# syslog-valve: no flows applied yet\noptions {\n    keep-hostname(yes);\n    use-dns(no);\n    time-reopen(2);\n};\n", version)
}

func name(n graph.Node) string {
	if n.Name != "" {
		return n.Name
	}
	return n.ID
}
