// Package codegen compiles a flow graph into a syslog-ng configuration and
// a matching logrotate config for cache nodes.
package codegen

import (
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/syslog-yard/syslog-valve/internal/graph"
	"github.com/syslog-yard/syslog-valve/internal/mitre"
)

// Shares maps a share name to its mount point (e.g. archive -> /shares/archive).
type Shares map[string]string

// The valve's TLS identity for IN ports: generated self-signed from the UI
// or mounted by the deployment. Forward verification uses the system CA
// bundle (mount extra CAs into /etc/ssl/certs).
const (
	CertFile = "/data/certs/valve.crt"
	KeyFile  = "/data/certs/valve.key"
	CADir    = "/etc/ssl/certs"
)

// TapSocket is the unix datagram socket the Go app listens on; every
// source duplicates its stream there for the UI's live tail.
const TapSocket = "/data/syslog-ng/tap.sock"

// NotifySocket is a second unix datagram socket: messages routed into a
// notify node are duplicated here, tagged with the node ident, for the Go
// notification dispatcher to deliver (S9 valve notify).
const NotifySocket = "/data/syslog-ng/notify.sock"

// Generate renders the full syslog-ng.conf for g. version is the
// "@version" directive value and should match the running syslog-ng
// (it tolerates older config versions with a warning, not the reverse).
func Generate(g *graph.Graph, version string, shares Shares) (string, error) {
	if err := g.Validate(); err != nil {
		return "", err
	}
	var b strings.Builder
	fmt.Fprintf(&b, "@version: %s\n", version)
	b.WriteString("# Generated by syslog-valve — do not edit; change the graph instead.\n\n")
	b.WriteString("options {\n    keep-hostname(yes);\n    use-dns(no);\n    time-reopen(2);\n};\n")

	elseFilters := elseBranches(g)
	for _, n := range g.Nodes {
		switch n.Type {
		case graph.TypeSource:
			bind := n.Config.Bind
			if bind == "" {
				bind = "0.0.0.0"
			}
			tls := ""
			if n.Config.Transport == "tls" {
				tls = fmt.Sprintf(" tls(key-file(%q) cert-file(%q) peer-verify(optional-untrusted))", KeyFile, CertFile)
			}
			fmt.Fprintf(&b, "\n# source %s\nsource s_%s {\n    network(ip(%q) transport(%q) port(%d)%s);\n};\n",
				name(n), graph.Ident(n.ID), bind, n.Config.Transport, n.Config.Port, tls)
		case graph.TypeForward:
			tls := ""
			if n.Config.Transport == "tls" {
				if n.Config.TLSVerify {
					tls = fmt.Sprintf(" tls(peer-verify(required-trusted) ca-dir(%q))", CADir)
				} else {
					tls = " tls(peer-verify(optional-untrusted))"
				}
			}
			fmt.Fprintf(&b, "\n# forward %s\ndestination d_%s {\n    network(%q port(%d) transport(%q)%s);\n};\n",
				name(n), graph.Ident(n.ID), n.Config.Host, n.Config.Port, n.Config.Transport, tls)
		case graph.TypeCache:
			p, err := CachePath(n, shares)
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&b, "\n# cache %s\ndestination d_%s {\n    file(%q create-dirs(yes));\n};\n",
				name(n), graph.Ident(n.ID), p)
		case graph.TypeNotify:
			// Matched messages are duplicated to the notify socket, tagged
			// with the node ident; the Go dispatcher delivers them. The
			// template mirrors the tap's, plus ${LEVEL} for the alert text.
			id := graph.Ident(n.ID)
			fmt.Fprintf(&b, "\n# notify %s\ndestination d_%s {\n    unix-dgram(%q persist-name(\"notify_%s\") template(\"%s\\t${ISODATE}\\t${HOST}\\t${PROGRAM}\\t${LEVEL}\\t${MSG}\\n\"));\n};\n",
				name(n), id, NotifySocket, id, id)
		case graph.TypeFilter:
			expr, err := filterExpr(n)
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&b, "\n# filter %s\nfilter f_%s {\n    %s;\n};\n", name(n), graph.Ident(n.ID), expr)
			if elseFilters[n.ID] {
				fmt.Fprintf(&b, "filter f_%s_else {\n    not filter(f_%s);\n};\n",
					graph.Ident(n.ID), graph.Ident(n.ID))
			}
		}
	}

	paths := flowPaths(g)
	if len(paths) > 0 {
		b.WriteString("\n")
	}
	for _, p := range paths {
		b.WriteString("log {\n")
		fmt.Fprintf(&b, "    source(s_%s);\n", graph.Ident(p.source))
		for _, st := range p.steps {
			suffix := ""
			if st.negated {
				suffix = "_else"
			}
			fmt.Fprintf(&b, "    filter(f_%s%s);\n", graph.Ident(st.filterID), suffix)
		}
		fmt.Fprintf(&b, "    destination(d_%s);\n};\n", graph.Ident(p.sink))
	}

	// Live tail: every source also feeds the app's tap socket; the
	// template ident lets the UI label messages with their IN port.
	for _, n := range g.Nodes {
		if n.Type != graph.TypeSource {
			continue
		}
		id := graph.Ident(n.ID)
		// Explicit persist-name: multiple destinations on one socket path
		// otherwise collide at startup (a runtime error --syntax-only
		// doesn't catch).
		fmt.Fprintf(&b, "\n# live tail tap for %s\ndestination d_tap_%s {\n    unix-dgram(%q persist-name(\"tap_%s\") template(\"%s\\t${ISODATE}\\t${HOST}\\t${PROGRAM}\\t${MSG}\\n\"));\n};\n",
			name(n), id, TapSocket, id, id)
		fmt.Fprintf(&b, "log {\n    source(s_%s);\n    destination(d_tap_%s);\n};\n", id, id)
	}
	return b.String(), nil
}

// GenerateLogrotate renders the logrotate config covering all cache nodes.
// Returns "" when the graph has none.
func GenerateLogrotate(g *graph.Graph, shares Shares) (string, error) {
	var b strings.Builder
	for _, n := range g.Nodes {
		if n.Type != graph.TypeCache {
			continue
		}
		p, err := CachePath(n, shares)
		if err != nil {
			return "", err
		}
		rotate := n.Config.Rotate
		if rotate == 0 {
			rotate = 7
		}
		fmt.Fprintf(&b, "# cache %s\n%s {\n", name(n), p)
		b.WriteString("    missingok\n    notifempty\n")
		// copytruncate so syslog-ng's open fd keeps working (and survives
		// SMB shares where rename-under-writer misbehaves)
		b.WriteString("    copytruncate\n")
		fmt.Fprintf(&b, "    rotate %d\n", rotate)
		if n.Config.MaxSizeMB > 0 {
			fmt.Fprintf(&b, "    size %dM\n", n.Config.MaxSizeMB)
		} else {
			b.WriteString("    daily\n")
		}
		if n.Config.MaxAgeDays > 0 {
			fmt.Fprintf(&b, "    maxage %d\n", n.Config.MaxAgeDays)
		}
		if n.Config.Compress {
			b.WriteString("    compress\n    delaycompress\n")
		}
		b.WriteString("}\n")
	}
	return b.String(), nil
}

// CachePath resolves a cache node to the file syslog-ng writes.
func CachePath(n graph.Node, shares Shares) (string, error) {
	base := "/data/cache"
	if loc := n.Config.Location; loc != "" {
		mount, ok := shares[loc]
		if !ok {
			return "", fmt.Errorf("cache %q: share %q is not configured (YARD_SHARES)", name(n), loc)
		}
		base = mount
	}
	dir := n.Config.Dir
	if dir == "" {
		dir = graph.Ident(n.ID)
	}
	return path.Join(base, dir, "messages.log"), nil
}

// Minimal returns a valid config with no flows, used before the first apply.
func Minimal(version string) string {
	return fmt.Sprintf("@version: %s\n# syslog-valve: no flows applied yet\noptions {\n    keep-hostname(yes);\n    use-dns(no);\n    time-reopen(2);\n};\n", version)
}

func filterExpr(n graph.Node) (string, error) {
	var conds []string
	if sm := n.Config.SeverityMax; sm != nil {
		conds = append(conds, fmt.Sprintf("level(emerg..%s)", graph.SeverityNames[*sm]))
	}
	if p := strings.TrimSpace(n.Config.Program); p != "" {
		conds = append(conds, fmt.Sprintf("program(%q)", p))
	}
	if m := strings.TrimSpace(n.Config.Match); m != "" {
		conds = append(conds, fmt.Sprintf("message(%q)", m))
	}
	// A MITRE technique compiles to its syslog-ng pattern (message regex
	// and/or program), so a flow can route or drop by technique (S8).
	if tid := n.Config.Technique; tid != "" {
		t, ok := mitre.Lookup(tid)
		if !ok {
			return "", fmt.Errorf("filter %q: unknown MITRE technique %q", name(n), tid)
		}
		if t.Program != "" {
			conds = append(conds, fmt.Sprintf("program(%q)", t.Program))
		}
		if t.Message != "" {
			conds = append(conds, fmt.Sprintf("message(%q)", t.Message))
		}
	}
	if len(conds) == 0 {
		return "", fmt.Errorf("filter %q has no conditions", name(n))
	}
	return strings.Join(conds, " and "), nil
}

type step struct {
	filterID string
	negated  bool
}

type flowPath struct {
	source string
	steps  []step
	sink   string
}

// flowPaths walks every source through filter chains to each reachable
// sink, one log {} block per complete path. Validate has already ruled
// out cycles.
func flowPaths(g *graph.Graph) []flowPath {
	var out []flowPath
	var walk func(srcID, nodeID string, steps []step)
	walk = func(srcID, nodeID string, steps []step) {
		for _, e := range g.EdgesFrom(nodeID) {
			next := g.Node(e.To)
			cur := append([]step(nil), steps...)
			if from := g.Node(nodeID); from.Type == graph.TypeFilter {
				cur = append(cur, step{filterID: nodeID, negated: e.FromPort == graph.PortElse})
			}
			switch next.Type {
			case graph.TypeFilter:
				walk(srcID, next.ID, cur)
			case graph.TypeForward, graph.TypeCache, graph.TypeNotify:
				out = append(out, flowPath{source: srcID, steps: cur, sink: next.ID})
			}
		}
	}
	for _, n := range g.Nodes {
		if n.Type == graph.TypeSource {
			walk(n.ID, n.ID, nil)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].source != out[j].source {
			return out[i].source < out[j].source
		}
		return out[i].sink < out[j].sink
	})
	return out
}

// elseBranches reports which filters have an else edge and so need the
// negated companion filter emitted.
func elseBranches(g *graph.Graph) map[string]bool {
	out := map[string]bool{}
	for _, e := range g.Edges {
		if e.FromPort == graph.PortElse {
			out[e.From] = true
		}
	}
	return out
}

func name(n graph.Node) string {
	if n.Name != "" {
		return n.Name
	}
	return n.ID
}
